### ISSUE TITLE
Error in plugin "gulp-postcss"

### ISSUE THREAD

**Issue by vdaltonrobles** [uswds/uswds-gulp#25]
### When running gulp-init I get the following error:

[21:04:29] 'build-sass' errored after 7.82 s
[21:04:29] Error in plugin "gulp-postcss"
Message:
    [object Object] is not a PostCSS plugin
Details:
    fileName: C:\Users\winDev3Admin\source\repos\VDR.Presentation\VDR.Presentation\_sass\styles.css
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (C:\Users\winDev3Admin\source\repos\VDR.Presentation\VDR.Presentation\node_modules\postcss\lib\processor.js:168:15)
    at new Processor (C:\Users\winDev3Admin\source\repos\VDR.Presentation\VDR.Presentation\node_modules\postcss\lib\processor.js:52:25)
    at postcss (C:\Users\winDev3Admin\source\repos\VDR.Presentation\VDR.Presentation\node_modules\postcss\lib\postcss.js:55:10)
    at C:\Users\winDev3Admin\source\repos\VDR.Presentation\VDR.Presentation\node_modules\gulp-postcss\index.js:50:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[21:04:29] 'init' errored after 8.96 s

### **Here is the package.json:**
{
  "name": "vdr.presentation",
  "version": "1.0.0",
  "description": "Demo",
  "main": "index.cshtml",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "VDR",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^10.0.0",
    "gulp": "^4.0.0",
    "gulp-notify": "^3.2.0",
    "gulp-postcss": "^8.0.0",
    "gulp-replace": "^1.0.0",
    "gulp-sass": "^4.1.0",
    "gulp-sourcemaps": "^2.6.5",
    "postcss-csso": "^4.0.0",
    "sass": "^1.26.10",
    "uswds": "^2.8.1",
    "uswds-gulp": "github:uswds/uswds-gulp"
  }
}

**Comment by taylorsolomon** [comment]
@vdaltonrobles I think you and I spotted the same issue at around the same time (see #26). If you install `autoprefixer@^9.8.6` it might resolve the issue for now. As far as I can tell it's related to a breaking change in how PostCSS handles plugins.

**Comment by vdaltonrobles** [comment]
Yes – I saw your response and did it.  It works for now.

Thank you,

Veronica Dalton-Robles
