### ISSUE TITLE
VirtualBox VM installation is not working

### ISSUE THREAD

**Issue by JasonWeakley** [uswds/uswds-gulp#30]
I am trying to get the npm packages installed, but I am unable to. Has anyone successfully built a VirtualBox VM with Drupal 9, and gotten these packages installed?

Current errors look like this:
```vagrant@drupalvm:/var/www/drupalvm/drupal/web$ npm install autoprefixer@^9.8.6
npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "autoprefixer@^9.8.6"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "autoprefixer@^9.8.6"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path npm-debug.log.2279232577
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.2279232577' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/drupalvm/drupal/web/npm-debug.log```

**Comment by JasonWeakley** [comment]
So I have updated node to v14.15.3, and npm to 6.14.9 and I am unable to install autoprfixer and other packages listed in the README.
```
vagrant@drupalvm:/var/www/drupalvm/drupal$ npm install gulp
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/var/www/drupalvm/drupal/package.json'
npm WARN drupal No description
npm WARN drupal No repository field.
npm WARN drupal No README data
npm WARN drupal No license field.

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /var/www/drupalvm/drupal/node_modules/array-initial/node_modules/is-number/package.json.1426398553
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/drupalvm/drupal/node_modules/array-initial/node_modules/is-number/package.json.1426398553'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm-cache/_logs/2020-12-28T17_42_20_083Z-debug.log
```

**Comment by JasonWeakley** [comment]
With some help I discovered a way around by simply copying and pasting the USWDS assets into an assets/ directory of the subdirectory. Then made a call to the assets/css/uswds.css file in the libraries.yml of the subtheme. But the ability to get npm and packages listed in the requirements here is broken.
